image:
  repository: docker.io/aeonlucid/impostor
  pullPolicy: IfNotPresent
  tag: v1.10.2@sha256:3d7908876104f83aac9ac2a9f02103599652fff14ef9a85cfe8e991e8316b767
nightlyImage:
  repository: aeonlucid/impostor
  tag: nightly@sha256:0dc8e95b5ea9a2ff2360c88c2990e58d2dcda9ccfb58715c31a9a4fc0aab9f6a
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: udp
        port: 22023
        targetPort: 22023
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            IMPOSTOR_Server__PublicIp: "127.0.0.1"
            IMPOSTOR_Server__ListenIp: "0.0.0.0"
            IMPOSTOR_AntiCheat__Enabled: true
            IMPOSTOR_AntiCheat__BanIpFromGame: true
            IMPOSTOR_Debug__GameRecorderEnabled: false
            IMPOSTOR_Debug__GameRecorderPath: ""
updated: true
