image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/bakito/adguardhome-sync
  tag: v0.6.17@sha256:5c872b757f828173c89fdd16db170776f0e2a919cfc8d35372fab60caacb5f33
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          args:
          - run
          env:
            CRON: "*/10 * * * *"
            FEATURES_CLIENTSETTINGS: "true"
            FEATURES_DHCP_SERVERCONFIG: "true"
            FEATURES_DHCP_STATICLEASES: "true"
            FEATURES_DNS_ACCESSLISTS: "true"
            FEATURES_DNS_REWRITES: "true"
            FEATURES_DNS_SERVERCONFIG: "true"
            FEATURES_FILTERS: "true"
            FEATURES_GENERALSETTINGS: "true"
            FEATURES_QUERYLOGCONFIG: "true"
            FEATURES_SERVICES: "true"
            FEATURES_STATSCONFIG: "true"
            ORIGIN_PASSWORD: password
            ORIGIN_URL: https://192.168.1.2:3000
            ORIGIN_USERNAME: username
            REPLICA_AUTOSETUP: "false"
            REPLICA_INTERFACENAME: ""
            REPLICA_PASSWORD: password
            REPLICA_URL: http://192.168.1.3
            REPLICA_USERNAME: username
            RUNONSTART: "true"
