image:
  repository: docker.io/portainer/portainer-ce
  tag: 2.25.1@sha256:c8aefc42eb902fc301a17fe151ceef24f02025feb4c9fdfffe5bd9234d777a42
  pullPolicy: IfNotPresent
beImage:
  repository: portainer/portainer-ee
  tag: 2.20.3@sha256:afadde3ae572f2346d0e04965171f6f1d2f1d06023796053c327e183c75d6cc6
  pullPolicy: IfNotPresent
portainer:
  # Logo URL
  logo: ""
  # Enables Edge Compute Features
  edge_compute: false
  # Sets Snapshot interval
  snapshot_interval: 5m
  hide_labels:
  # - label1=value1
  # - label2=value2
serviceAccount:
  main:
    enabled: true
    primary: true
rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
    - apiGroups:
      - "*"
      resources:
      - "*"
      verbs:
      - "*"
service:
  main:
    ports:
      main:
        port: 10400
        protocol: https
        targetPort: 9443
  edge:
    enabled: true
    ports:
      edge:
        enabled: true
        port: 10401
        targetPort: 10401
persistence:
  data:
    enabled: true
    mountPath: "/data"
  cache:
    enabled: true
    mountPath: "/.cache"
    type: emptyDir
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      automountServiceAccountToken: true
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              port: 9443
              type: https
            readiness:
              port: 9443
              type: https
            startup:
              port: 9443
              type: https
updated: true
