image:
  repository: "koush/scrypted"
  tag: "v0.117.3-jammy-full@sha256:152c4f963631fad9ad2f8a883ec1ebdadc990d09521ab022b3b4ae36847cae7d"
  pullPolicy: "Always"
liteImage:
  repository: koush/scrypted
  tag: 
    v0.105.0-jammy-lite@sha256:2daca814cf03d24a022c3298fef387535fed72b4e0fa50420e8775f68a5fae86
  pullPolicy: Always
nvidiaImage:
  repository: koush/scrypted
  tag: 
    v0.105.0-jammy-nvidia@sha256:2ae3ceb8268ccf8e5632c82e122130d2389d57d356bc113386b3f124d8a78e40
  pullPolicy: Always

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 10611

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            SCRYPTED_INSECURE_PORT: "{{ .Values.service.main.ports.main.port }}"
            # SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: Bearer SET_THIS_TO_SOME_RANDOM_TEXT
            # SCRYPTED_WEBHOOK_UPDATE: http://localhost:10444/v1/update

persistence:
  server:
    enabled: true
    mountPath: /server/volume
  media:
    enabled: true
    mountPath: /media/external

portal:
  open:
    enabled: true
