image:
  pullPolicy: "IfNotPresent"
  repository: "redislabs/redisinsight"
  tag: "2.58.0@sha256:c3885a6b0fe11b7f33001c0586af0a82101f9a4ab83d5af55f1904f5fc642815"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10579
redisinsight:
  log_level: WARNING
  trusted_origins: []
  auth_prompt: false
  auth_timer: 30
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RIPORT: "{{ .Values.service.main.ports.main.port }}"
            RIHOMEDIR: /config
            RILOGDIR: /logs
            RILOGLEVEL: "{{ .Values.redisinsight.log_level }}"
            RITRUSTEDORIGINS: '{{ join "," .Values.redisinsight.trusted_origins }}'
            RIAUTHPROMPT: "{{ .Values.redisinsight.auth_prompt }}"
            RIAUTHTIMER: "{{ .Values.redisinsight.auth_timer }}"
persistence:
  config:
    enabled: true
    mountPath: /config
  logs:
    enabled: true
    mountPath: /logs
portal:
  open:
    enabled: true
